export const PlayerLimits = {
    MAX_GOALKEEPERS: 1,
    TOTAL_GOALKEEPERS: 2,
    MAX_DEFENDERS: 5,
    MIN_DEFENDERS: 3,
    TOTAL_DEFENDERS: 5,
    MAX_MIDFIELDERS: 5,
    MIN_MIDFIELDERS: 2,
    TOTAL_MIDFIELDERS: 5,
    MAX_FORWARDS: 4,
    MIN_FORWARDS: 1,
    TOTAL_FORWARDS: 4,
    TOTAL_STARTERS: 11,
}